apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-tickets
  template:
    metadata:
      labels:
        app: ticket-tickets
    spec:
      containers:
        - name: ticket-tickets
          image: pennycho/ticket-tickets
          env:
            - name: MONGO_URI
              value: "mongodb://ticket-tickets-mongo-srv:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-tickets-srv
spec:
  selector:
    app: ticket-tickets
  ports:
    - name: ticket-tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
